valor_a, valor_b, valor_c =input().split()
valor_a=float(valor_a)
valor_b=float(valor_b)
valor_c=float(valor_c)
print('TRIANGULO:', "%.3f" % (valor_a * valor_c / 2))
print('CIRCULO:', "%.3f" % (valor_c ** 2 * 3.14159))
print('TRAPEZIO:', "%.3f" % (((valor_a + valor_b) * valor_c) / 2))
print('QUADRADO:', "%.3f" % (valor_b ** 2))
print('RETANGULO:', "%.3f" % (valor_a * valor_b))